### ISSUE TITLE
Define Project Goals and Audience

### ISSUE THREAD

**Issue by panler** [minh-swinburne/cos30045-project#4]
- Determine the primary audience.
- Decide the main questions our visualization will answer.

**Comment by minh-swinburne** [comment]
- [ ]  Github Repository - created
- [ ] Communication Channel: Messenger
- [ ] Shared documentation: Google Drive folder
- [ ] Project Schedule

**Comment by nerfedatt** [comment]
### Primary Audience

- Public Health Officials and Policy Makers: To provide insights that could guide health policies focused on preventive care.
- Health Researchers and Analysts: For those interested in the correlation between lifestyle choices and health outcomes across populations.
- General Public (Health-Conscious Individuals): To raise awareness about the health impacts of common lifestyle factors.

### Project Goals

- Visualize Connections: Show how specific lifestyle choices (e.g., smoking, alcohol consumption) correlate with health outcomes (e.g., chronic disease prevalence, mortality rates).
- Highlight Patterns Across Countries: Allow users to compare countries, seeing how lifestyle factors differ and potentially affect health outcomes.
- Promote Awareness and Actionable Insights: Equip viewers with an understanding of high-risk behaviors and encourage policy decisions or personal lifestyle changes.

### Key Questions the Visualization Will Answer

1. How do rates of smoking, alcohol consumption, and physical inactivity differ across countries? (Interactive Choropleth)
2. How do risk factors for health change across countries over years? (Horizontal bar chart race between countries over years, with filter for each risk factor)
3. How do risk factors correlate with poor health outcomes? (Interactive bubble chart, with filters for time and both axes, each bubble representing a gender - distinguished by color, from a country. bubble size representing number of people.)
4. How have lifestyle trends change over years? (Line chart, each line representing a risk factor, filters for country and year.)
5. What is the share of population for obese and overweight across countries? (Stacked bar chart, filter for year)

**Comment by nerfedatt** [comment]
### IMPORTANT: Topic changed to focus on Alcohol

---

### Project Title

Alcohol and Health: Consumption, Consequences, and Control 

---

### **Project Objectives**

1. **Analyze Alcohol Consumption Patterns**  
   - **Objective:** Provide an overview of global and demographic patterns in alcohol consumption by breaking down data by country, type of alcohol, gender, and age. This will highlight where consumption is highest, what types of alcohol are most popular, and which demographics are more inclined to consume alcohol.
  
2. **Investigate Health and Social Consequences**  
   - **Objective:** Examine the impact of alcohol consumption on health outcomes and social issues, such as liver disease, traffic accidents, and mental health disorders. This will help illustrate the potential risks associated with different levels and patterns of alcohol use.

3. **Evaluate the Effectiveness of Alcohol Control Policies**  
   - **Objective:** Show how various countries’ policies (e.g., taxes, sales restrictions, advertising bans) align with consumption rates and health outcomes. By visualizing these relationships, the project can identify potential policy measures that correlate with reduced consumption and better health outcomes.

4. **Track Changes Over Time**  
   - **Objective:** Analyze how alcohol consumption trends have evolved over recent decades and assess the impact of major events (e.g., COVID-19 pandemic) on these trends. This helps in understanding the dynamic nature of alcohol consumption and its changing impact on health and society.

5. **Provide an Interactive, User-Friendly Exploration Tool**  
   - **Objective:** Develop a website that hosts these visualizations interactively, allowing users to explore specific questions or trends of interest by filtering by country, type of alcohol, demographic group, or year. The goal is to make data accessible and engaging, enhancing users' understanding of alcohol as a lifestyle factor.

---

### **Target Audience**

1. **Public Health Officials and Policymakers**  
   - *Interest:* Understanding the scope of alcohol-related health issues and how policy measures might reduce negative outcomes. The visualizations offer data-driven insights into effective policies and highlight areas for intervention.

2. **Researchers and Academics in Public Health and Social Sciences**  
   - *Interest:* Analyzing cross-country and demographic comparisons to study the impact of alcohol consumption on public health. This project provides a rich dataset and an accessible way to explore associations between alcohol use and health outcomes.

3. **Nonprofit Organizations and Health Advocates**  
   - *Interest:* Supporting advocacy for healthier lifestyle choices and policies that reduce harmful alcohol consumption. The project data can help these organizations create targeted campaigns or policy recommendations.

4. **General Public and Health-Conscious Individuals**  
   - *Interest:* Gaining awareness of how alcohol consumption patterns and risks vary across regions and demographics. Interactive charts offer a digestible way to learn about the health risks associated with alcohol and explore data by country or demographic.

5. **Media and Data Journalists**  
   - *Interest:* Accessing clear and interactive visuals to report on alcohol consumption trends, health impacts, and policies. The data can support stories on lifestyle trends, health risks, or policy effectiveness.

---

### Key Areas for Analysis

1. **Alcohol Consumption Patterns**

   - By Type: Analyze preferences for wine, beer, and spirits across different countries.

   - By Demographics: Break down consumption by gender and age groups to uncover patterns in different population segments.

2. **Consequences of Alcohol Consumption**

   - Health Outcomes: Highlight alcohol-related health issues like liver disease, cardiovascular problems, and addiction disorders.
   - Social and Economic Impact: Include data on alcohol-related traffic accidents, crime rates, and economic costs, emphasizing the broader impact on society.

3. **Policies and Controls**

   - Taxation and Pricing Policies: Show how alcohol taxes affect consumption rates, comparing countries with higher vs. lower taxes.
   - Regulations: Include any bans, minimum age laws, or restricted sales hours, and analyze their effectiveness in reducing consumption or harmful outcomes.
